### ISSUE TITLE
Review supported labels in the provider and add those missing

### ISSUE THREAD

**Issue by lawrencegripper** [containous/traefik-extra-service-fabric#3]
As raised by @naeemkhedarun we are currently missing support for passTLSCert. 

I propose using this issue to capture all labels which we may be missing and then creating a related PR to add the functionality.

**Comment by lawrencegripper** [comment]
Here is a list of additional configuration which is not currently available in Traefik with Service Fabric.

@ldez - In the current template I used generic functions like `getLabelValue` and `hasLabel` but I can see you have added a more explicit function when fixing the bug #5. Is this the preferred way to do this work?

@naeemkhedarun - If you have a chance to take a look can you check if there are any missing from this list? 

### Pass TLS Cert

``` toml 
[frontends]
  [frontends.frontend2]
  backend = "backend1"
  passTLSCert = true
```

### Custom Response Headers 

``` toml
[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.headers.customresponseheaders]
    X-Custom-Response-Header = "True"
    [frontends.frontend1.headers.customrequestheaders]
    X-Script-Name = "test"
    [frontends.frontend1.routes.test_1]
    rule = "PathPrefixStrip:/cheese"
```

### Security Headers

``` toml
[frontends]
  [frontends.frontend1]
  backend = "backend1"
    [frontends.frontend1.headers]
    FrameDeny = true
    [frontends.frontend1.routes.test_1]
    rule = "PathPrefixStrip:/cheddar"
  [frontends.frontend2]
  backend = "backend2"
    [frontends.frontend2.headers]
    SSLRedirect = true
    [frontends.frontend2.routes.test_1]
    rule = "PathPrefixStrip:/stilton"

```

### Rate Limiting

Currently, as Service Fabric runs one instance of Traefik per node in the cluster behind a load balancer, I believe rate limiting would not function as expected. Investigate whether [HA/Clustering](https://master--traefik-docs.netlify.com/user-guide/cluster/) could be used. 

Options:
1. Add the labels as users could configure the deployment to run as a singleton if they wanted to utilize ratelimited. Downsides: For most users rate limiting wouldn't function as expected. For users who did configure the service as a singleton they would loose HA if the node was stopped. 
2. Don't add the label for rate limiting until we're able to support it on SF in a HA way.  Investigate whether [HA/Clustering](https://master--traefik-docs.netlify.com/user-guide/cluster/) could be used and look to support in the future, if possible. <- **This is my preference.**
